language: node_js
node_js:
  - "9.8.0"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - cp backend/config/database.ci.js backend/config/database.js
  - psql -c 'create database mymoney_ci_test;' -U postgres
script:
  - npm run prettier:check
  - npm run lint
  - npm run test